### ISSUE TITLE
create/does>

### ISSUE THREAD

**Issue by wboeke** [CCurl/c3#35]
How should I use create and does> in c3? These words are in c3.c, but not in the README.
I tried a simple example:
: val create , does> @ 10 * ;
5 val five
five .
The expected output is 50, but all I get is a crash.

**Comment by CCurl** [comment]
I think it's the ", @" that is causing the crash. Here is an example of how I use it:

![image](https://github.com/CCurl/c3/assets/14334380/60986ca4-f4f4-4d0f-ac9a-ba8dd36f8bca)

**Comment by CCurl** [comment]
OK, so I have made it behave more like a standard Forth in this respect. 

CREATE xxx will add xxx to the dictionary and, when you execute xxx, it will put VHERE on the stack.

Note that CREATE only starts the word off ... it creates a word that has no EXIT, so a word that uses it will have to complete the definition, either by using "does>", or by doing whatever you define it to do and then ending with "(exit) c,".

For example ... these are words in c3 ...

: variable  create 0 v, (exit) c, ;
: val       create 0 v, does> @ ;
: >val      create does> cell - ! ;

usage ...
val line >val >line
17 >line
line \ prints 17

... and your test ...
: test create v, does> @ 10 * . ;
17 test abc
44 test def
abc \ prints 170
def \ prints 440

**Comment by wboeke** [comment]
You are great, it works!
I was considering to drop c3, however then I would miss its clever string handling and good hackability. I made the words 'see' and 'words' in C, you cannot do that in pure forth, but they are in my opinion the visiting-card of a forth implementation.

**Comment by CCurl** [comment]
> I made the words 'see' and 'words' in C, you cannot do that in pure forth

Did you do that in c3? c3 already has 'words', which is written in c3. You can find the implementation in the sys-load.h file.

Did you create support for 'see' in the c3 project? If so, would you mind sharing it with me? 

I created a word I called 'dis' that outputs a 'disassembly' of the word here. But it is currently out of date, because I rearranged some of the c3 opcodes in this latest version, and I haven't gone back and updated it yet. You would use it like this: "dis words". I need to go back to that and bring it up to date. Or update c3.c to support it natively. :)

https://github.com/CCurl/Projects/blob/main/c3/dis.c3

**Comment by CCurl** [comment]
... and thanks for trying my stuff out! I know it can be a pain when the documentation is incomplete (or non-existent!). I intend to document the "baked-in" c3 words, either in the README or in a Wiki page, but I haven't done that yet ... sorry!

**Comment by wboeke** [comment]
About 'words': if a word is longer then 7 characters, then the output at the right side wil become ragged. The solution is to output one word less at that line. Maybe this can be done in forth, but it will be complicated. In C it's easy, and also the 'see' word:

void doWords() {
  dict_t *dp = last; int n=0, total=0;
  while (dp < (dict_t*)&code[CODE_SZ]) {
    printf("%s",dp->name); ++n; ++total;
    if (strlen(dp->name) > 7) ++n;
    if (n > 7) { n= 0; fputc('\n', stdout); }
    else fputc('\t', stdout);
    ++dp;
  }
  printf("\n%d words\n",total);
}
void doSee() {
  t1=nextWord();
  if (doFind(WD)) fputs("okay", stdout); else fputs("unknown", stdout);
}

**Comment by CCurl** [comment]
Here is WORDS in c3 code:
![image](https://github.com/CCurl/c3/assets/14334380/45ed2ab1-9eae-4f73-a086-96db6421c507)

**Comment by CCurl** [comment]
Re doSee() ... did you add a line to ParseLine() to call it? Or how does it get executed?

![image](https://github.com/CCurl/c3/assets/14334380/97ae060e-37bb-4035-8576-b5fa7db290ea)

**Comment by wboeke** [comment]
The forth code in your 'words' is the same as in the last c3 repository. It's output shows that ragged lines I complained about.
  
About 'see': no, I added a case statement to void Run(), just like other words:
NCASE SEE: toSee(0);
Of course also an extra enum value SEE. I tried to do the same in your c4, but I couldn't find out how. C3 is hackable, c4 is too clever for me...

**Comment by CCurl** [comment]
LOL ... you are too nice ... "clever" is not the word I would use. :)

So a new opcode ... cool. I would recommend adding to the list of "system" opcodes. It's arbitrary I know, but to keep the number of cases in the main SWITCH down, I try to only have the 1-char opcodes to those operations that have to be as fast as possible.

If you want to do a pull request for it, we can add it as a built-in word. Let me know, thanks.

**Comment by CCurl** [comment]
> About 'words': if a word is longer then 7 characters, then the output at the right side wil become ragged. The solution is to output one word less at that line. Maybe this can be done in forth, but it will be complicated. In C it's easy, and also the 'see' word:
> 
This seems to work ... I added 'word-len' (a--n) and a check to 'words'. 'r2' is the address of the current word.

![image](https://github.com/CCurl/c3/assets/14334380/1f400ad0-b99a-43a0-9056-7f2fe8fd1442)
