### ISSUE TITLE
Arduino: for every char typed a space is stored in tib

### ISSUE THREAD

**Issue by henk1955** [CCurl/c3#54]
108     *(in++) = (31<c) ? 32 : c;

I changed it to: *(in++) = (c<31) ? 32 : c;

**Comment by CCurl** [comment]
Thanks! I haven't gotten far enough on using/debugging it with an Arduino device. I keep getting sidetracked with other things.

It's good (and somewhat unexpected) to learn that someone other than me is actually using my stuff. I ohpe it works for you! What board are you using?

I will update the branch :)

**Comment by henk1955** [comment]
NodeMCU 1.0 (ESP12E), Board Libraries 3.1.2, Arduino IDE 1.18.19.

I made changes to c3.h    #define CODE_SZ            16*1024
    #define VARS_SZ            16*1024
    #define STK_SZ            256
    #define LSTK_SZ             3*25      // 25 nested loops
    #define REGS_SZ            10*25      // 25 nested +REGS
    #define TIB_SZ            128
    #define NAME_LEN           12
    #define NEEDS_ALIGN
    #define _SYS_LOAD_
    #define _LITTLEFS_

and file.cpp to make it work with LittleFS

**Comment by CCurl** [comment]
Awesome. Can you send me the file.cpp or post it here so I can update it in the source?

**Comment by CCurl** [comment]
Re these:

#define LSTK_SZ 325 // 25 nested loops
#define REGS_SZ 1025 // 25 nested +REGS

LSTK_SZ should be a power of 3, as each loop entry uses 3 values (lo, hi, addr)
So 25 nested loops would be 75.
REGS_SZ should be a power of 10, as +REGS/-REGS modifies the base index (reg_base) by 10.
And 25 nested +REGS would be 250.

**Comment by henk1955** [comment]
I forgot to use `<>`
`    #define CODE_SZ            16*1024
    #define VARS_SZ            16*1024
    #define STK_SZ            256
    #define LSTK_SZ             3*25      // 25 nested loops
    #define REGS_SZ            10*25      // 25 nested +REGS
    #define TIB_SZ            128
    #define NAME_LEN           12
    #define NEEDS_ALIGN
    #define _SYS_LOAD_
    #define _LITTLEFS_`

can not upload .cpp files

**Comment by CCurl** [comment]
It looks like you forked the repo. FWIW, the Arduino branch has the latest stuff (mostly a bunch of small tweaks), but it also has the editor.
